using System.Collections.Generic;

namespace DotNetPow.Web.Icons.DotNetPowFlags
{
    /// <summary>
    /// Static definitions for DotNetPowFlags
    /// </summary>
    public static class StaticDotNetPowFlagDefinitions
    {
        /// <summary>
        /// Prefix for all .Net Pow! Flags CSS Classes
        /// </summary>
        public const string DotNetPowCssClassPrefix = "dot-net-pow-flags";

        /// <summary>
        /// Image map
        /// </summary>
        public static Dictionary<DotNetPowFlagNames, string> DotNetPowFlagImages = new Dictionary<DotNetPowFlagNames, string>
        {
            { DotNetPowFlagNames.Afghanistan, "af.png" },
            { DotNetPowFlagNames.Aland_Islands, "ax.png" },
            { DotNetPowFlagNames.Albania, "al.png" },
            { DotNetPowFlagNames.Algeria, "dz.png" },
            { DotNetPowFlagNames.American_Samoa, "as.png" },
            { DotNetPowFlagNames.Andorra, "ad.png" },
            { DotNetPowFlagNames.Angola, "ao.png" },
            { DotNetPowFlagNames.Anguilla, "ai.png" },
            { DotNetPowFlagNames.Antarctica, "aq.png" },
            { DotNetPowFlagNames.Antigua_And_Barbuda, "ag.png" },
            { DotNetPowFlagNames.Argentina, "ar.png" },
            { DotNetPowFlagNames.Armenia, "am.png" },
            { DotNetPowFlagNames.Aruba, "aw.png" },
            { DotNetPowFlagNames.Australia, "au.png" },
            { DotNetPowFlagNames.Austria, "at.png" },
            { DotNetPowFlagNames.Azerbaijan, "az.png" },
            { DotNetPowFlagNames.Bahamas, "bs.png" },
            { DotNetPowFlagNames.Bahrain, "bh.png" },
            { DotNetPowFlagNames.Bangladesh, "bd.png" },
            { DotNetPowFlagNames.Barbados, "bb.png" },
            { DotNetPowFlagNames.Belarus, "by.png" },
            { DotNetPowFlagNames.Belgium, "be.png" },
            { DotNetPowFlagNames.Belize, "bz.png" },
            { DotNetPowFlagNames.Benin, "bj.png" },
            { DotNetPowFlagNames.Bermuda, "bm.png" },
            { DotNetPowFlagNames.Bhutan, "bt.png" },
            { DotNetPowFlagNames.Bolivia, "bo.png" },
            { DotNetPowFlagNames.Bosnia_And_Herzegovina, "ba.png" },
            { DotNetPowFlagNames.Botswana, "bw.png" },
            { DotNetPowFlagNames.Brazil, "br.png" },
            { DotNetPowFlagNames.British_Indian_Ocean_Territory, "io.png" },
            { DotNetPowFlagNames.British_Virgin_Islands, "vg.png" },
            { DotNetPowFlagNames.Brunei, "bn.png" },
            { DotNetPowFlagNames.Bulgaria, "bg.png" },
            { DotNetPowFlagNames.Burkina_Faso, "bf.png" },
            { DotNetPowFlagNames.Burundi, "bi.png" },
            { DotNetPowFlagNames.Cambodia, "kh.png" },
            { DotNetPowFlagNames.Cameroon, "cm.png" },
            { DotNetPowFlagNames.Canada, "ca.png" },
            { DotNetPowFlagNames.Cape_Verde, "cv.png" },
            { DotNetPowFlagNames.Cayman_Islands, "ky.png" },
            { DotNetPowFlagNames.Central_African_Republic, "cf.png" },
            { DotNetPowFlagNames.Chad, "td.png" },
            { DotNetPowFlagNames.Chile, "cl.png" },
            { DotNetPowFlagNames.China, "cn.png" },
            { DotNetPowFlagNames.Christmas_Island, "cx.png" },
            { DotNetPowFlagNames.Cocos_Islands, "cc.png" },
            { DotNetPowFlagNames.Colombia, "co.png" },
            { DotNetPowFlagNames.Comoros, "km.png" },
            { DotNetPowFlagNames.Cook_Islands, "ck.png" },
            { DotNetPowFlagNames.Costa_Rica, "cr.png" },
            { DotNetPowFlagNames.Croatia, "hr.png" },
            { DotNetPowFlagNames.Cuba, "cu.png" },
            { DotNetPowFlagNames.Curacao, "cw.png" },
            { DotNetPowFlagNames.Cyprus, "cy.png" },
            { DotNetPowFlagNames.Czech_Republic, "cz.png" },
            { DotNetPowFlagNames.Democratic_Republic_of_the_Congo, "cd.png" },
            { DotNetPowFlagNames.Denmark, "dk.png" },
            { DotNetPowFlagNames.Djibouti, "dj.png" },
            { DotNetPowFlagNames.Dominica, "dm.png" },
            { DotNetPowFlagNames.Dominican_Republic, "do.png" },
            { DotNetPowFlagNames.East_Timor, "tl.png" },
            { DotNetPowFlagNames.Ecuador, "ec.png" },
            { DotNetPowFlagNames.Egypt, "eg.png" },
            { DotNetPowFlagNames.El_Salvador, "sv.png" },
            { DotNetPowFlagNames.Equatorial_Guinea, "gq.png" },
            { DotNetPowFlagNames.Eritrea, "er.png" },
            { DotNetPowFlagNames.Estonia, "ee.png" },
            { DotNetPowFlagNames.Ethiopia, "et.png" },
            { DotNetPowFlagNames.Falkland_Islands, "fk.png" },
            { DotNetPowFlagNames.Faroe_Islands, "fo.png" },
            { DotNetPowFlagNames.Fiji, "fj.png" },
            { DotNetPowFlagNames.Finland, "fi.png" },
            { DotNetPowFlagNames.France, "fr.png" },
            { DotNetPowFlagNames.French_Guiana, "gf.png" },
            { DotNetPowFlagNames.French_Polynesia, "pf.png" },
            { DotNetPowFlagNames.Gabon, "ga.png" },
            { DotNetPowFlagNames.Gambia, "gm.png" },
            { DotNetPowFlagNames.Georgia, "ge.png" },
            { DotNetPowFlagNames.Germany, "de.png" },
            { DotNetPowFlagNames.Ghana, "gh.png" },
            { DotNetPowFlagNames.Gibraltar, "gi.png" },
            { DotNetPowFlagNames.Greece, "gr.png" },
            { DotNetPowFlagNames.Greenland, "gl.png" },
            { DotNetPowFlagNames.Grenada, "gd.png" },
            { DotNetPowFlagNames.Guadeloupe, "gp.png" },
            { DotNetPowFlagNames.Guam, "gu.png" },
            { DotNetPowFlagNames.Guatemala, "gt.png" },
            { DotNetPowFlagNames.Guernsey, "gg.png" },
            { DotNetPowFlagNames.Guinea, "gn.png" },
            { DotNetPowFlagNames.Guinea_Bissau, "gw.png" },
            { DotNetPowFlagNames.Guyana, "gy.png" },
            { DotNetPowFlagNames.Haiti, "ht.png" },
            { DotNetPowFlagNames.Honduras, "hn.png" },
            { DotNetPowFlagNames.Hong_Kong, "hk.png" },
            { DotNetPowFlagNames.Hungary, "hu.png" },
            { DotNetPowFlagNames.Iceland, "is.png" },
            { DotNetPowFlagNames.India, "in.png" },
            { DotNetPowFlagNames.Indonesia, "id.png" },
            { DotNetPowFlagNames.Iran, "ir.png" },
            { DotNetPowFlagNames.Iraq, "iq.png" },
            { DotNetPowFlagNames.Ireland, "ie.png" },
            { DotNetPowFlagNames.Isle_of_Man, "im.png" },
            { DotNetPowFlagNames.Israel, "il.png" },
            { DotNetPowFlagNames.Italy, "it.png" },
            { DotNetPowFlagNames.Ivory_Coast, "ci.png" },
            { DotNetPowFlagNames.Jamaica, "jm.png" },
            { DotNetPowFlagNames.Japan, "jp.png" },
            { DotNetPowFlagNames.Jersey, "je.png" },
            { DotNetPowFlagNames.Jordan, "jo.png" },
            { DotNetPowFlagNames.Kazakhstan, "kz.png" },
            { DotNetPowFlagNames.Kenya, "ke.png" },
            { DotNetPowFlagNames.Kiribati, "ki.png" },
            { DotNetPowFlagNames.Kosovo, "xk.png" },
            { DotNetPowFlagNames.Kuwait, "kw.png" },
            { DotNetPowFlagNames.Kyrgyzstan, "kg.png" },
            { DotNetPowFlagNames.Laos, "la.png" },
            { DotNetPowFlagNames.Latvia, "lv.png" },
            { DotNetPowFlagNames.Lebanon, "lb.png" },
            { DotNetPowFlagNames.Lesotho, "ls.png" },
            { DotNetPowFlagNames.Liberia, "lr.png" },
            { DotNetPowFlagNames.Libya, "ly.png" },
            { DotNetPowFlagNames.Liechtenstein, "li.png" },
            { DotNetPowFlagNames.Lithuania, "lt.png" },
            { DotNetPowFlagNames.Luxembourg, "lu.png" },
            { DotNetPowFlagNames.Macau, "mo.png" },
            { DotNetPowFlagNames.Macedonia, "mk.png" },
            { DotNetPowFlagNames.Madagascar, "mg.png" },
            { DotNetPowFlagNames.Malawi, "mw.png" },
            { DotNetPowFlagNames.Malaysia, "my.png" },
            { DotNetPowFlagNames.Maldives, "mv.png" },
            { DotNetPowFlagNames.Mali, "ml.png" },
            { DotNetPowFlagNames.Malta, "mt.png" },
            { DotNetPowFlagNames.Marshall_Islands, "mh.png" },
            { DotNetPowFlagNames.Martinique, "mq.png" },
            { DotNetPowFlagNames.Mauritania, "mr.png" },
            { DotNetPowFlagNames.Mauritius, "mu.png" },
            { DotNetPowFlagNames.Mayotte, "yt.png" },
            { DotNetPowFlagNames.Mexico, "mx.png" },
            { DotNetPowFlagNames.Micronesia, "fm.png" },
            { DotNetPowFlagNames.Moldova, "md.png" },
            { DotNetPowFlagNames.Monaco, "mc.png" },
            { DotNetPowFlagNames.Mongolia, "mn.png" },
            { DotNetPowFlagNames.Montenegro, "me.png" },
            { DotNetPowFlagNames.Montserrat, "ms.png" },
            { DotNetPowFlagNames.Morocco, "ma.png" },
            { DotNetPowFlagNames.Mozambique, "mz.png" },
            { DotNetPowFlagNames.Myanmar, "mm.png" },
            { DotNetPowFlagNames.Namibia, "na.png" },
            { DotNetPowFlagNames.Nauru, "nr.png" },
            { DotNetPowFlagNames.Nepal, "np.png" },
            { DotNetPowFlagNames.Netherlands, "nl.png" },
            { DotNetPowFlagNames.Netherlands_Antilles, "nl.png" },
            { DotNetPowFlagNames.New_Caledonia, "nc.png" },
            { DotNetPowFlagNames.New_Zealand, "nz.png" },
            { DotNetPowFlagNames.Nicaragua, "ni.png" },
            { DotNetPowFlagNames.Niger, "ne.png" },
            { DotNetPowFlagNames.Nigeria, "ng.png" },
            { DotNetPowFlagNames.Niue, "nu.png" },
            { DotNetPowFlagNames.North_Korea, "kp.png" },
            { DotNetPowFlagNames.Northern_Mariana_Islands, "mp.png" },
            { DotNetPowFlagNames.Norway, "no.png" },
            { DotNetPowFlagNames.Oman, "om.png" },
            { DotNetPowFlagNames.Pakistan, "pk.png" },
            { DotNetPowFlagNames.Palau, "pw.png" },
            { DotNetPowFlagNames.Palestine, "ps.png" },
            { DotNetPowFlagNames.Panama, "pa.png" },
            { DotNetPowFlagNames.Papua_New_Guinea, "pg.png" },
            { DotNetPowFlagNames.Paraguay, "py.png" },
            { DotNetPowFlagNames.Peru, "pe.png" },
            { DotNetPowFlagNames.Philippines, "ph.png" },
            { DotNetPowFlagNames.Pitcairn, "pn.png" },
            { DotNetPowFlagNames.Poland, "pl.png" },
            { DotNetPowFlagNames.Portugal, "pt.png" },
            { DotNetPowFlagNames.Puerto_Rico, "pr.png" },
            { DotNetPowFlagNames.Qatar, "qa.png" },
            { DotNetPowFlagNames.Republic_of_the_Congo, "cg.png" },
            { DotNetPowFlagNames.Reunion, "re.png" },
            { DotNetPowFlagNames.Romania, "ro.png" },
            { DotNetPowFlagNames.Russia, "ru.png" },
            { DotNetPowFlagNames.Rwanda, "rw.png" },
            { DotNetPowFlagNames.Saint_Barthelemy, "bl.png" },
            { DotNetPowFlagNames.Saint_Helena, "sh.png" },
            { DotNetPowFlagNames.Saint_Kitts_And_Nevis, "kn.png" },
            { DotNetPowFlagNames.Saint_Lucia, "lc.png" },
            { DotNetPowFlagNames.Saint_Martin, "mf.png" },
            { DotNetPowFlagNames.Saint_Pierre_And_Miquelon, "pm.png" },
            { DotNetPowFlagNames.Saint_Vincent_And_the_Grenadines, "vc.png" },
            { DotNetPowFlagNames.Samoa, "ws.png" },
            { DotNetPowFlagNames.San_Marino, "sm.png" },
            { DotNetPowFlagNames.Sao_Tome_And_Principe, "st.png" },
            { DotNetPowFlagNames.Saudi_Arabia, "sa.png" },
            { DotNetPowFlagNames.Senegal, "sn.png" },
            { DotNetPowFlagNames.Serbia, "rs.png" },
            { DotNetPowFlagNames.Seychelles, "sc.png" },
            { DotNetPowFlagNames.Sierra_Leone, "sl.png" },
            { DotNetPowFlagNames.Singapore, "sg.png" },
            { DotNetPowFlagNames.Sint_Maarten, "sx.png" },
            { DotNetPowFlagNames.Slovakia, "sk.png" },
            { DotNetPowFlagNames.Slovenia, "si.png" },
            { DotNetPowFlagNames.Solomon_Islands, "sb.png" },
            { DotNetPowFlagNames.Somalia, "so.png" },
            { DotNetPowFlagNames.South_Africa, "za.png" },
            { DotNetPowFlagNames.South_Korea, "kr.png" },
            { DotNetPowFlagNames.South_Sudan, "ss.png" },
            { DotNetPowFlagNames.Spain, "es.png" },
            { DotNetPowFlagNames.Sri_Lanka, "lk.png" },
            { DotNetPowFlagNames.Sudan, "sd.png" },
            { DotNetPowFlagNames.Suriname, "sr.png" },
            { DotNetPowFlagNames.Svalbard_And_Jan_Mayen, "sj.png" },
            { DotNetPowFlagNames.Swaziland, "sz.png" },
            { DotNetPowFlagNames.Sweden, "se.png" },
            { DotNetPowFlagNames.Switzerland, "ch.png" },
            { DotNetPowFlagNames.Syria, "sy.png" },
            { DotNetPowFlagNames.Taiwan, "tw.png" },
            { DotNetPowFlagNames.Tajikistan, "tj.png" },
            { DotNetPowFlagNames.Tanzania, "tz.png" },
            { DotNetPowFlagNames.Thailand, "th.png" },
            { DotNetPowFlagNames.Togo, "tg.png" },
            { DotNetPowFlagNames.Tokelau, "tk.png" },
            { DotNetPowFlagNames.Tonga, "to.png" },
            { DotNetPowFlagNames.Trinidad_And_Tobago, "tt.png" },
            { DotNetPowFlagNames.Tunisia, "tn.png" },
            { DotNetPowFlagNames.Turkey, "tr.png" },
            { DotNetPowFlagNames.Turkmenistan, "tm.png" },
            { DotNetPowFlagNames.Turks_And_Caicos_Islands, "tc.png" },
            { DotNetPowFlagNames.Tuvalu, "tv.png" },
            { DotNetPowFlagNames.US_Virgin_Islands, "vi.png" },
            { DotNetPowFlagNames.Uganda, "ug.png" },
            { DotNetPowFlagNames.Ukraine, "ua.png" },
            { DotNetPowFlagNames.United_Arab_Emirates, "ae.png" },
            // -------------------------------------------------------------------------------------------------------------------------
            { DotNetPowFlagNames.United_Kingdom, "gb.png" },
            { DotNetPowFlagNames.Northern_Ireland, "gb-nir.png" },
            { DotNetPowFlagNames.England, "gb-eng.png" },
            {DotNetPowFlagNames.Scotland, "gb-sct.png" },
            { DotNetPowFlagNames.Wales, "gb-wls.png" },
            // -------------------------------------------------------------------------------------------------------------------------
            { DotNetPowFlagNames.United_States, "us.png" },
            { DotNetPowFlagNames.Uruguay, "uy.png" },
            { DotNetPowFlagNames.Uzbekistan, "uz.png" },
            { DotNetPowFlagNames.Vanuatu, "vu.png" },
            { DotNetPowFlagNames.Vatican, "va.png" },
            { DotNetPowFlagNames.Venezuela, "ve.png" },
            { DotNetPowFlagNames.Vietnam, "vn.png" },
            { DotNetPowFlagNames.Wallis_And_Futuna, "wf.png" },
            { DotNetPowFlagNames.Western_Sahara, "eh.png" },
            { DotNetPowFlagNames.Yemen, "ye.png" },
            { DotNetPowFlagNames.Zambia, "zm.png" },
            { DotNetPowFlagNames.Zimbabwe, "zw.png" },

            { DotNetPowFlagNames.Caribbean_Netherlands, "bq.png" },
            { DotNetPowFlagNames.Bouvet_Island, "bv.png" },
            { DotNetPowFlagNames.South_Georgia, "gs.png" },
            { DotNetPowFlagNames.Heard_McDonald_Islands, "hm.png" },
            { DotNetPowFlagNames.Territory_Norfolk_Island, "nf.png" },
            { DotNetPowFlagNames.French_Southern_Antarctic_Lands, "tf.png" },

            { DotNetPowFlagNames.DotNetPow, "dot-net-pow.png" },
            { DotNetPowFlagNames.DotNetPowAlt, "dot-net-pow-alt.png" }
        };

        /// <summary>
        /// Css map
        /// </summary>
        public static readonly Dictionary<DotNetPowFlagNames, string> DotNetPowFlagsCssClassNames = new Dictionary<DotNetPowFlagNames, string>
        {
            { DotNetPowFlagNames.Afghanistan, DotNetPowCssClassPrefix + " afghanistan" },
            { DotNetPowFlagNames.Aland_Islands, DotNetPowCssClassPrefix + " aland-islands" },
            { DotNetPowFlagNames.Albania, DotNetPowCssClassPrefix + " albania" },
            { DotNetPowFlagNames.Algeria, DotNetPowCssClassPrefix + " algeria" },
            { DotNetPowFlagNames.American_Samoa, DotNetPowCssClassPrefix + " american-samoa" },
            { DotNetPowFlagNames.Andorra, DotNetPowCssClassPrefix + " andorra" },
            { DotNetPowFlagNames.Angola, DotNetPowCssClassPrefix + " angola" },
            { DotNetPowFlagNames.Anguilla, DotNetPowCssClassPrefix + " anguilla" },
            { DotNetPowFlagNames.Antarctica, DotNetPowCssClassPrefix + " antarctica" },
            { DotNetPowFlagNames.Antigua_And_Barbuda, DotNetPowCssClassPrefix + " antigua-and-barbuda" },
            { DotNetPowFlagNames.Argentina, DotNetPowCssClassPrefix + " argentina" },
            { DotNetPowFlagNames.Armenia, DotNetPowCssClassPrefix + " armenia" },
            { DotNetPowFlagNames.Aruba, DotNetPowCssClassPrefix + " aruba" },
            { DotNetPowFlagNames.Australia, DotNetPowCssClassPrefix + " australia" },
            { DotNetPowFlagNames.Austria, DotNetPowCssClassPrefix + " austria" },
            { DotNetPowFlagNames.Azerbaijan, DotNetPowCssClassPrefix + " azerbaijan" },
            { DotNetPowFlagNames.Bahamas, DotNetPowCssClassPrefix + " bahamas" },
            { DotNetPowFlagNames.Bahrain, DotNetPowCssClassPrefix + " bahrain" },
            { DotNetPowFlagNames.Bangladesh, DotNetPowCssClassPrefix + " bangladesh" },
            { DotNetPowFlagNames.Barbados, DotNetPowCssClassPrefix + " barbados" },
            { DotNetPowFlagNames.Belarus, DotNetPowCssClassPrefix + " belarus" },
            { DotNetPowFlagNames.Belgium, DotNetPowCssClassPrefix + " belgium" },
            { DotNetPowFlagNames.Belize, DotNetPowCssClassPrefix + " belize" },
            { DotNetPowFlagNames.Benin, DotNetPowCssClassPrefix + " benin" },
            { DotNetPowFlagNames.Bermuda, DotNetPowCssClassPrefix + " bermuda" },
            { DotNetPowFlagNames.Bhutan, DotNetPowCssClassPrefix + " bhutan" },
            { DotNetPowFlagNames.Bolivia, DotNetPowCssClassPrefix + " bolivia" },
            { DotNetPowFlagNames.Bosnia_And_Herzegovina, DotNetPowCssClassPrefix + " bosnia-and-herzegovina" },
            { DotNetPowFlagNames.Botswana, DotNetPowCssClassPrefix + " botswana" },
            { DotNetPowFlagNames.Brazil, DotNetPowCssClassPrefix + " brazil" },
            { DotNetPowFlagNames.British_Indian_Ocean_Territory, DotNetPowCssClassPrefix + " british-indian-ocean-territory" },
            { DotNetPowFlagNames.British_Virgin_Islands, DotNetPowCssClassPrefix + " british-virgin-islands" },
            { DotNetPowFlagNames.Brunei, DotNetPowCssClassPrefix + " brunei" },
            { DotNetPowFlagNames.Bulgaria, DotNetPowCssClassPrefix + " bulgaria" },
            { DotNetPowFlagNames.Burkina_Faso, DotNetPowCssClassPrefix + " burkina-faso" },
            { DotNetPowFlagNames.Burundi, DotNetPowCssClassPrefix + " burundi" },
            { DotNetPowFlagNames.Cambodia, DotNetPowCssClassPrefix + " cambodia" },
            { DotNetPowFlagNames.Cameroon, DotNetPowCssClassPrefix + " cameroon" },
            { DotNetPowFlagNames.Canada, DotNetPowCssClassPrefix + " canada" },
            { DotNetPowFlagNames.Cape_Verde, DotNetPowCssClassPrefix + " cape-verde" },
            { DotNetPowFlagNames.Cayman_Islands, DotNetPowCssClassPrefix + " cayman-islands" },
            { DotNetPowFlagNames.Central_African_Republic, DotNetPowCssClassPrefix + " central-african-republic" },
            { DotNetPowFlagNames.Chad, DotNetPowCssClassPrefix + " chad" },
            { DotNetPowFlagNames.Chile, DotNetPowCssClassPrefix + " chile" },
            { DotNetPowFlagNames.China, DotNetPowCssClassPrefix + " china" },
            { DotNetPowFlagNames.Christmas_Island, DotNetPowCssClassPrefix + " christmas-island" },
            { DotNetPowFlagNames.Cocos_Islands, DotNetPowCssClassPrefix + " cocos-islands" },
            { DotNetPowFlagNames.Colombia, DotNetPowCssClassPrefix + " colombia" },
            { DotNetPowFlagNames.Comoros, DotNetPowCssClassPrefix + " comoros" },
            { DotNetPowFlagNames.Cook_Islands, DotNetPowCssClassPrefix + " cook-islands" },
            { DotNetPowFlagNames.Costa_Rica, DotNetPowCssClassPrefix + " costa-rica" },
            { DotNetPowFlagNames.Croatia, DotNetPowCssClassPrefix + " croatia" },
            { DotNetPowFlagNames.Cuba, DotNetPowCssClassPrefix + " cuba" },
            { DotNetPowFlagNames.Curacao, DotNetPowCssClassPrefix + " curacao" },
            { DotNetPowFlagNames.Cyprus, DotNetPowCssClassPrefix + " cyprus" },
            { DotNetPowFlagNames.Czech_Republic, DotNetPowCssClassPrefix + " czech-republic" },
            { DotNetPowFlagNames.Democratic_Republic_of_the_Congo, DotNetPowCssClassPrefix + " democratic-republic-of-the-congo" },
            { DotNetPowFlagNames.Denmark, DotNetPowCssClassPrefix + " denmark" },
            { DotNetPowFlagNames.Djibouti, DotNetPowCssClassPrefix + " djibouti" },
            { DotNetPowFlagNames.Dominica, DotNetPowCssClassPrefix + " dominica" },
            { DotNetPowFlagNames.Dominican_Republic, DotNetPowCssClassPrefix + " dominican-republic" },
            { DotNetPowFlagNames.East_Timor, DotNetPowCssClassPrefix + " east-timor" },
            { DotNetPowFlagNames.Ecuador, DotNetPowCssClassPrefix + " ecuador" },
            { DotNetPowFlagNames.Egypt, DotNetPowCssClassPrefix + " egypt" },
            { DotNetPowFlagNames.El_Salvador, DotNetPowCssClassPrefix + " el-salvador" },
            { DotNetPowFlagNames.Equatorial_Guinea, DotNetPowCssClassPrefix + " equatorial-guinea" },
            { DotNetPowFlagNames.Eritrea, DotNetPowCssClassPrefix + " eritrea" },
            { DotNetPowFlagNames.Estonia, DotNetPowCssClassPrefix + " estonia" },
            { DotNetPowFlagNames.Ethiopia, DotNetPowCssClassPrefix + " ethiopia" },
            { DotNetPowFlagNames.Falkland_Islands, DotNetPowCssClassPrefix + " falkland-islands" },
            { DotNetPowFlagNames.Faroe_Islands, DotNetPowCssClassPrefix + " faroe-islands" },
            { DotNetPowFlagNames.Fiji, DotNetPowCssClassPrefix + " fiji" },
            { DotNetPowFlagNames.Finland, DotNetPowCssClassPrefix + " finland" },
            { DotNetPowFlagNames.France, DotNetPowCssClassPrefix + " france" },
            { DotNetPowFlagNames.French_Guiana, DotNetPowCssClassPrefix + " french-guiana" },
            { DotNetPowFlagNames.French_Polynesia, DotNetPowCssClassPrefix + " french-polynesia" },
            { DotNetPowFlagNames.Gabon, DotNetPowCssClassPrefix + " gabon" },
            { DotNetPowFlagNames.Gambia, DotNetPowCssClassPrefix + " gambia" },
            { DotNetPowFlagNames.Georgia, DotNetPowCssClassPrefix + " georgia" },
            { DotNetPowFlagNames.Germany, DotNetPowCssClassPrefix + " germany" },
            { DotNetPowFlagNames.Ghana, DotNetPowCssClassPrefix + " ghana" },
            { DotNetPowFlagNames.Gibraltar, DotNetPowCssClassPrefix + " gibraltar" },
            { DotNetPowFlagNames.Greece, DotNetPowCssClassPrefix + " greece" },
            { DotNetPowFlagNames.Greenland, DotNetPowCssClassPrefix + " greenland" },
            { DotNetPowFlagNames.Grenada, DotNetPowCssClassPrefix + " grenada" },
            { DotNetPowFlagNames.Guadeloupe, DotNetPowCssClassPrefix + " guadeloupe" },
            { DotNetPowFlagNames.Guam, DotNetPowCssClassPrefix + " guam" },
            { DotNetPowFlagNames.Guatemala, DotNetPowCssClassPrefix + " guatemala" },
            { DotNetPowFlagNames.Guernsey, DotNetPowCssClassPrefix + " guernsey" },
            { DotNetPowFlagNames.Guinea, DotNetPowCssClassPrefix + " guinea" },
            { DotNetPowFlagNames.Guinea_Bissau, DotNetPowCssClassPrefix + " guinea-bissau" },
            { DotNetPowFlagNames.Guyana, DotNetPowCssClassPrefix + " guyana" },
            { DotNetPowFlagNames.Haiti, DotNetPowCssClassPrefix + " haiti" },
            { DotNetPowFlagNames.Honduras, DotNetPowCssClassPrefix + " honduras" },
            { DotNetPowFlagNames.Hong_Kong, DotNetPowCssClassPrefix + " hong-kong" },
            { DotNetPowFlagNames.Hungary, DotNetPowCssClassPrefix + " hungary" },
            { DotNetPowFlagNames.Iceland, DotNetPowCssClassPrefix + " iceland" },
            { DotNetPowFlagNames.India, DotNetPowCssClassPrefix + " india" },
            { DotNetPowFlagNames.Indonesia, DotNetPowCssClassPrefix + " indonesia" },
            { DotNetPowFlagNames.Iran, DotNetPowCssClassPrefix + " iran" },
            { DotNetPowFlagNames.Iraq, DotNetPowCssClassPrefix + " iraq" },
            { DotNetPowFlagNames.Ireland, DotNetPowCssClassPrefix + " ireland" },
            { DotNetPowFlagNames.Isle_of_Man, DotNetPowCssClassPrefix + " isle-of-man" },
            { DotNetPowFlagNames.Israel, DotNetPowCssClassPrefix + " israel" },
            { DotNetPowFlagNames.Italy, DotNetPowCssClassPrefix + " italy" },
            { DotNetPowFlagNames.Ivory_Coast, DotNetPowCssClassPrefix + " ivory-coast" },
            { DotNetPowFlagNames.Jamaica, DotNetPowCssClassPrefix + " jamaica" },
            { DotNetPowFlagNames.Japan, DotNetPowCssClassPrefix + " japan" },
            { DotNetPowFlagNames.Jersey, DotNetPowCssClassPrefix + " jersey" },
            { DotNetPowFlagNames.Jordan, DotNetPowCssClassPrefix + " jordan" },
            { DotNetPowFlagNames.Kazakhstan, DotNetPowCssClassPrefix + " kazakhstan" },
            { DotNetPowFlagNames.Kenya, DotNetPowCssClassPrefix + " kenya" },
            { DotNetPowFlagNames.Kiribati, DotNetPowCssClassPrefix + " kiribati" },
            { DotNetPowFlagNames.Kosovo, DotNetPowCssClassPrefix + " kosovo" },
            { DotNetPowFlagNames.Kuwait, DotNetPowCssClassPrefix + " kuwait" },
            { DotNetPowFlagNames.Kyrgyzstan, DotNetPowCssClassPrefix + " kyrgyzstan" },
            { DotNetPowFlagNames.Laos, DotNetPowCssClassPrefix + " laos" },
            { DotNetPowFlagNames.Latvia, DotNetPowCssClassPrefix + " latvia" },
            { DotNetPowFlagNames.Lebanon, DotNetPowCssClassPrefix + " lebanon" },
            { DotNetPowFlagNames.Lesotho, DotNetPowCssClassPrefix + " lesotho" },
            { DotNetPowFlagNames.Liberia, DotNetPowCssClassPrefix + " liberia" },
            { DotNetPowFlagNames.Libya, DotNetPowCssClassPrefix + " libya" },
            { DotNetPowFlagNames.Liechtenstein, DotNetPowCssClassPrefix + " liechtenstein" },
            { DotNetPowFlagNames.Lithuania, DotNetPowCssClassPrefix + " lithuania" },
            { DotNetPowFlagNames.Luxembourg, DotNetPowCssClassPrefix + " luxembourg" },
            { DotNetPowFlagNames.Macau, DotNetPowCssClassPrefix + " macau" },
            { DotNetPowFlagNames.Macedonia, DotNetPowCssClassPrefix + " macedonia" },
            { DotNetPowFlagNames.Madagascar, DotNetPowCssClassPrefix + " madagascar" },
            { DotNetPowFlagNames.Malawi, DotNetPowCssClassPrefix + " malawi" },
            { DotNetPowFlagNames.Malaysia, DotNetPowCssClassPrefix + " malaysia" },
            { DotNetPowFlagNames.Maldives, DotNetPowCssClassPrefix + " maldives" },
            { DotNetPowFlagNames.Mali, DotNetPowCssClassPrefix + " mali" },
            { DotNetPowFlagNames.Malta, DotNetPowCssClassPrefix + " malta" },
            { DotNetPowFlagNames.Marshall_Islands, DotNetPowCssClassPrefix + " marshall-islands" },
            { DotNetPowFlagNames.Martinique, DotNetPowCssClassPrefix + " martinique" },
            { DotNetPowFlagNames.Mauritania, DotNetPowCssClassPrefix + " mauritania" },
            { DotNetPowFlagNames.Mauritius, DotNetPowCssClassPrefix + " mauritius" },
            { DotNetPowFlagNames.Mayotte, DotNetPowCssClassPrefix + " mayotte" },
            { DotNetPowFlagNames.Mexico, DotNetPowCssClassPrefix + " mexico" },
            { DotNetPowFlagNames.Micronesia, DotNetPowCssClassPrefix + " micronesia" },
            { DotNetPowFlagNames.Moldova, DotNetPowCssClassPrefix + " moldova" },
            { DotNetPowFlagNames.Monaco, DotNetPowCssClassPrefix + " monaco" },
            { DotNetPowFlagNames.Mongolia, DotNetPowCssClassPrefix + " mongolia" },
            { DotNetPowFlagNames.Montenegro, DotNetPowCssClassPrefix + " montenegro" },
            { DotNetPowFlagNames.Montserrat, DotNetPowCssClassPrefix + " montserrat" },
            { DotNetPowFlagNames.Morocco, DotNetPowCssClassPrefix + " morocco" },
            { DotNetPowFlagNames.Mozambique, DotNetPowCssClassPrefix + " mozambique" },
            { DotNetPowFlagNames.Myanmar, DotNetPowCssClassPrefix + " myanmar" },
            { DotNetPowFlagNames.Namibia, DotNetPowCssClassPrefix + " namibia" },
            { DotNetPowFlagNames.Nauru, DotNetPowCssClassPrefix + " nauru" },
            { DotNetPowFlagNames.Nepal, DotNetPowCssClassPrefix + " nepal" },
            { DotNetPowFlagNames.Netherlands, DotNetPowCssClassPrefix + " netherlands" },
            { DotNetPowFlagNames.Netherlands_Antilles, DotNetPowCssClassPrefix + " netherlands-antilles" },
            { DotNetPowFlagNames.New_Caledonia, DotNetPowCssClassPrefix + " new-caledonia" },
            { DotNetPowFlagNames.New_Zealand, DotNetPowCssClassPrefix + " new-zealand" },
            { DotNetPowFlagNames.Nicaragua, DotNetPowCssClassPrefix + " nicaragua" },
            { DotNetPowFlagNames.Niger, DotNetPowCssClassPrefix + " niger" },
            { DotNetPowFlagNames.Nigeria, DotNetPowCssClassPrefix + " nigeria" },
            { DotNetPowFlagNames.Niue, DotNetPowCssClassPrefix + " niue" },
            { DotNetPowFlagNames.North_Korea, DotNetPowCssClassPrefix + " north-korea" },
            { DotNetPowFlagNames.Northern_Mariana_Islands, DotNetPowCssClassPrefix + " northern-mariana-islands" },
            { DotNetPowFlagNames.Norway, DotNetPowCssClassPrefix + " norway" },
            { DotNetPowFlagNames.Oman, DotNetPowCssClassPrefix + " oman" },
            { DotNetPowFlagNames.Pakistan, DotNetPowCssClassPrefix + " pakistan" },
            { DotNetPowFlagNames.Palau, DotNetPowCssClassPrefix + " palau" },
            { DotNetPowFlagNames.Palestine, DotNetPowCssClassPrefix + " palestine" },
            { DotNetPowFlagNames.Panama, DotNetPowCssClassPrefix + " panama" },
            { DotNetPowFlagNames.Papua_New_Guinea, DotNetPowCssClassPrefix + " papua-new-guinea" },
            { DotNetPowFlagNames.Paraguay, DotNetPowCssClassPrefix + " paraguay" },
            { DotNetPowFlagNames.Peru, DotNetPowCssClassPrefix + " peru" },
            { DotNetPowFlagNames.Philippines, DotNetPowCssClassPrefix + " philippines" },
            { DotNetPowFlagNames.Pitcairn, DotNetPowCssClassPrefix + " pitcairn" },
            { DotNetPowFlagNames.Poland, DotNetPowCssClassPrefix + " poland" },
            { DotNetPowFlagNames.Portugal, DotNetPowCssClassPrefix + " portugal" },
            { DotNetPowFlagNames.Puerto_Rico, DotNetPowCssClassPrefix + " puerto-rico" },
            { DotNetPowFlagNames.Qatar, DotNetPowCssClassPrefix + " qatar" },
            { DotNetPowFlagNames.Republic_of_the_Congo, DotNetPowCssClassPrefix + " republic-of-the-congo" },
            { DotNetPowFlagNames.Reunion, DotNetPowCssClassPrefix + " reunion" },
            { DotNetPowFlagNames.Romania, DotNetPowCssClassPrefix + " romania" },
            { DotNetPowFlagNames.Russia, DotNetPowCssClassPrefix + " russia" },
            { DotNetPowFlagNames.Rwanda, DotNetPowCssClassPrefix + " rwanda" },
            { DotNetPowFlagNames.Saint_Barthelemy, DotNetPowCssClassPrefix + " saint-barthelemy" },
            { DotNetPowFlagNames.Saint_Helena, DotNetPowCssClassPrefix + " saint-helena" },
            { DotNetPowFlagNames.Saint_Kitts_And_Nevis, DotNetPowCssClassPrefix + " saint-kitts-and-nevis" },
            { DotNetPowFlagNames.Saint_Lucia, DotNetPowCssClassPrefix + " saint-lucia" },
            { DotNetPowFlagNames.Saint_Martin, DotNetPowCssClassPrefix + " saint-martin" },
            { DotNetPowFlagNames.Saint_Pierre_And_Miquelon, DotNetPowCssClassPrefix + " saint-pierre-and-miquelon" },
            { DotNetPowFlagNames.Saint_Vincent_And_the_Grenadines, DotNetPowCssClassPrefix + " saint-vincent-and-the-grenadines" },
            { DotNetPowFlagNames.Samoa, DotNetPowCssClassPrefix + " samoa" },
            { DotNetPowFlagNames.San_Marino, DotNetPowCssClassPrefix + " san-marino" },
            { DotNetPowFlagNames.Sao_Tome_And_Principe, DotNetPowCssClassPrefix + " sao-tome-and-principe" },
            { DotNetPowFlagNames.Saudi_Arabia, DotNetPowCssClassPrefix + " saudi-arabia" },
            { DotNetPowFlagNames.Senegal, DotNetPowCssClassPrefix + " senegal" },
            { DotNetPowFlagNames.Serbia, DotNetPowCssClassPrefix + " serbia" },
            { DotNetPowFlagNames.Seychelles, DotNetPowCssClassPrefix + " seychelles" },
            { DotNetPowFlagNames.Sierra_Leone, DotNetPowCssClassPrefix + " sierra-leone" },
            { DotNetPowFlagNames.Singapore, DotNetPowCssClassPrefix + " singapore" },
            { DotNetPowFlagNames.Sint_Maarten, DotNetPowCssClassPrefix + " sint-maarten" },
            { DotNetPowFlagNames.Slovakia, DotNetPowCssClassPrefix + " slovakia" },
            { DotNetPowFlagNames.Slovenia, DotNetPowCssClassPrefix + " slovenia" },
            { DotNetPowFlagNames.Solomon_Islands, DotNetPowCssClassPrefix + " solomon-islands" },
            { DotNetPowFlagNames.Somalia, DotNetPowCssClassPrefix + " somalia" },
            { DotNetPowFlagNames.South_Africa, DotNetPowCssClassPrefix + " south-africa" },
            { DotNetPowFlagNames.South_Korea, DotNetPowCssClassPrefix + " south-korea" },
            { DotNetPowFlagNames.South_Sudan, DotNetPowCssClassPrefix + " south-sudan" },
            { DotNetPowFlagNames.Spain, DotNetPowCssClassPrefix + " spain" },
            { DotNetPowFlagNames.Sri_Lanka, DotNetPowCssClassPrefix + " sri-lanka" },
            { DotNetPowFlagNames.Sudan, DotNetPowCssClassPrefix + " sudan" },
            { DotNetPowFlagNames.Suriname, DotNetPowCssClassPrefix + " suriname" },
            { DotNetPowFlagNames.Svalbard_And_Jan_Mayen, DotNetPowCssClassPrefix + " svalbard-and-jan-mayen" },
            { DotNetPowFlagNames.Swaziland, DotNetPowCssClassPrefix + " swaziland" },
            { DotNetPowFlagNames.Sweden, DotNetPowCssClassPrefix + " sweden" },
            { DotNetPowFlagNames.Switzerland, DotNetPowCssClassPrefix + " switzerland" },
            { DotNetPowFlagNames.Syria, DotNetPowCssClassPrefix + " syria" },
            { DotNetPowFlagNames.Taiwan, DotNetPowCssClassPrefix + " taiwan" },
            { DotNetPowFlagNames.Tajikistan, DotNetPowCssClassPrefix + " tajikistan" },
            { DotNetPowFlagNames.Tanzania, DotNetPowCssClassPrefix + " tanzania" },
            { DotNetPowFlagNames.Thailand, DotNetPowCssClassPrefix + " thailand" },
            { DotNetPowFlagNames.Togo, DotNetPowCssClassPrefix + " togo" },
            { DotNetPowFlagNames.Tokelau, DotNetPowCssClassPrefix + " tokelau" },
            { DotNetPowFlagNames.Tonga, DotNetPowCssClassPrefix + " tonga" },
            { DotNetPowFlagNames.Trinidad_And_Tobago, DotNetPowCssClassPrefix + " trinidad-and-tobago" },
            { DotNetPowFlagNames.Tunisia, DotNetPowCssClassPrefix + " tunisia" },
            { DotNetPowFlagNames.Turkey, DotNetPowCssClassPrefix + " turkey" },
            { DotNetPowFlagNames.Turkmenistan, DotNetPowCssClassPrefix + " turkmenistan" },
            { DotNetPowFlagNames.Turks_And_Caicos_Islands, DotNetPowCssClassPrefix + " turks-and-caicos-islands" },
            { DotNetPowFlagNames.Tuvalu, DotNetPowCssClassPrefix + " tuvalu" },
            { DotNetPowFlagNames.US_Virgin_Islands, DotNetPowCssClassPrefix + " us-virgin-islands" },
            { DotNetPowFlagNames.Uganda, DotNetPowCssClassPrefix + " uganda" },
            { DotNetPowFlagNames.Ukraine, DotNetPowCssClassPrefix + " ukraine" },
            { DotNetPowFlagNames.United_Arab_Emirates, DotNetPowCssClassPrefix + " united-arab-emirates" },
            { DotNetPowFlagNames.United_Kingdom, DotNetPowCssClassPrefix + " united-kingdom" },
            // -------------------------------------------------------------------------------------------------------------------------
            {DotNetPowFlagNames.England, DotNetPowCssClassPrefix + " england" },
            {DotNetPowFlagNames.Northern_Ireland, DotNetPowCssClassPrefix + " northern-ireland" },
            {DotNetPowFlagNames.Scotland, DotNetPowCssClassPrefix + " scotland" },
            {DotNetPowFlagNames.Wales, DotNetPowCssClassPrefix + " wales" },
            // -------------------------------------------------------------------------------------------------------------------------
            { DotNetPowFlagNames.United_States, DotNetPowCssClassPrefix + " united-states" },
            { DotNetPowFlagNames.Uruguay, DotNetPowCssClassPrefix + " uruguay" },
            { DotNetPowFlagNames.Uzbekistan, DotNetPowCssClassPrefix + " uzbekistan" },
            { DotNetPowFlagNames.Vanuatu, DotNetPowCssClassPrefix + " vanuatu" },
            { DotNetPowFlagNames.Vatican, DotNetPowCssClassPrefix + " vatican" },
            { DotNetPowFlagNames.Venezuela, DotNetPowCssClassPrefix + " venezuela" },
            { DotNetPowFlagNames.Vietnam, DotNetPowCssClassPrefix + " vietnam" },
            { DotNetPowFlagNames.Wallis_And_Futuna, DotNetPowCssClassPrefix + " wallis-and-futuna" },
            { DotNetPowFlagNames.Western_Sahara, DotNetPowCssClassPrefix + " western-sahara" },
            { DotNetPowFlagNames.Yemen, DotNetPowCssClassPrefix + " yemen" },
            { DotNetPowFlagNames.Zambia, DotNetPowCssClassPrefix + " zambia" },
            { DotNetPowFlagNames.Zimbabwe, DotNetPowCssClassPrefix + " zimbabwe" },

            { DotNetPowFlagNames.Caribbean_Netherlands, DotNetPowCssClassPrefix + " caribbean-netherlands" },
            { DotNetPowFlagNames.Bouvet_Island, DotNetPowCssClassPrefix + " bouvet-island" },
            { DotNetPowFlagNames.South_Georgia, DotNetPowCssClassPrefix + " south-georgia-and-the-south-sandwich-islands" },
            { DotNetPowFlagNames.Heard_McDonald_Islands, DotNetPowCssClassPrefix + " heard-island-and-mcdonald-islands" },
            { DotNetPowFlagNames.Territory_Norfolk_Island, DotNetPowCssClassPrefix + " territory-of-norfolk-island" },
            { DotNetPowFlagNames.French_Southern_Antarctic_Lands, DotNetPowCssClassPrefix + " french-southern-antarctic-lands" },

            { DotNetPowFlagNames.DotNetPow, DotNetPowCssClassPrefix + " dot-net-pow" },
            { DotNetPowFlagNames.DotNetPowAlt, DotNetPowCssClassPrefix + " dot-net-pow-alt" }
        };

        /// <summary>
        /// Size css map
        /// </summary>
        public static readonly Dictionary<DotNetPowFlagSizes, string> DotNetPowFlagSizeCssClassNames = new Dictionary<DotNetPowFlagSizes, string>
        {
            { DotNetPowFlagSizes.H20, "h20" },
            { DotNetPowFlagSizes.H24, "h24" },
            { DotNetPowFlagSizes.H48, "h48" },
            { DotNetPowFlagSizes.H80, "h80" },
            { DotNetPowFlagSizes.H120, "h120" },
            { DotNetPowFlagSizes.H160, "h160" },
            { DotNetPowFlagSizes.H240, "h240" },

            { DotNetPowFlagSizes.W320, "w320" },
            { DotNetPowFlagSizes.W550, "w550" },
            { DotNetPowFlagSizes.W640, "w640" },
            { DotNetPowFlagSizes.W702, "w702" },
            { DotNetPowFlagSizes.W1160, "w1160" },
            { DotNetPowFlagSizes.W2560, "w2560" }
        };
    }
}
